### ISSUE TITLE
cannot dump and load fixtures

### ISSUE THREAD

**Issue by mutax** [kelvinwong-ca/django-select-multiple-field#6]
I am using 
 ./manage.py  dumpdata -n -a --natural --indent=4 -e contenttypes -e sessions -e auth.Permission > dump.json 
and then try to import the data using
manage.py loaddata dump.json

This fails, because the value of the field is stored in an unexpected way in the json file. When I manually alter the file, the import seems to work.

non working:
        "acl_allowed_roles": "[u'st', u'ta', u'tu']",
 this is a json string, not a json list. 

When I alter the file to somethign like that it works:
        "acl_allowed_roles": ["st", "ta", "tu"],

I instrumented the code with some logging output.

$ ./manage.py  dumpdata -n -a --natural --indent=4 -e contenttypes -e sessions -e auth.Permission > dump2.json 
[05/Aug/2015 20:08:44] DEBUG [select_multiple:75] calling to_python with "st,ta,tu"
[05/Aug/2015 20:08:44] DEBUG [select_multiple:16] decoding "st,ta,tu" into list
[05/Aug/2015 20:08:44] DEBUG [select_multiple:23] returning "st,ta,tu" as list: [u'st', u'ta', u'tu']
...

$ ./manage.py loaddata dump2.json

[05/Aug/2015 20:13:44] DEBUG [select_multiple:75] calling to_python with "[u'st', u'ta', u'tu']"
[05/Aug/2015 20:13:44] DEBUG [select_multiple:16] decoding "[u'st', u'ta', u'tu']" into list
[05/Aug/2015 20:13:44] DEBUG [select_multiple:23] returning "[u'st', u'ta', u'tu']" as list: [u" u'ta'", u" u'tu']", u"[u'st'"]
[05/Aug/2015 20:13:44] DEBUG [select_multiple:75] calling to_python with "[u" u'ta'", u" u'tu']", u"[u'st'"]"
[05/Aug/2015 20:13:44] DEBUG [select_multiple:178] calling validate_options_list on [u" u'ta'", u" u'tu']", u"[u'st'"]
[05/Aug/2015 20:13:44] DEBUG [select_multiple:181] option is ' u'ta''
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python2.7/dist-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/lib/python2.7/dist-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python2.7/dist-packages/django/core/management/commands/loaddata.py", line 61, in handle
    self.loaddata(fixture_labels)
  File "/usr/lib/python2.7/dist-packages/django/core/management/commands/loaddata.py", line 91, in loaddata
    self.load_label(fixture_label)
  File "/usr/lib/python2.7/dist-packages/django/core/management/commands/loaddata.py", line 142, in load_label
    for obj in objects:
  File "/usr/lib/python2.7/dist-packages/django/core/serializers/json.py", line 81, in Deserializer
    six.reraise(DeserializationError, DeserializationError(e), sys.exc_info()[2])
  File "/usr/lib/python2.7/dist-packages/django/core/serializers/json.py", line 75, in Deserializer
    for obj in PythonDeserializer(objects, **options):
  File "/usr/lib/python2.7/dist-packages/django/core/serializers/python.py", line 147, in Deserializer
    obj = base.build_instance(Model, data, db)
  File "/usr/lib/python2.7/dist-packages/django/core/serializers/base.py", line 190, in build_instance
    obj = Model(**data)
  File "/usr/lib/python2.7/dist-packages/django/db/models/base.py", line 442, in __init__
    setattr(self, field.attname, val)
  File "/usr/lib/python2.7/dist-packages/django/db/models/fields/subclassing.py", line 37, in __set__
    obj.__dict__[self.field.name] = self.field.to_python(value)
  File ".../select_multiple_field/models.py", line 81, in to_python
    self.validate_options_list(value)
  File ".../select_multiple_field/models.py", line 184, in validate_options_list
    raise exceptions.ValidationError(msg)
django.core.serializers.base.DeserializationError: Problem installing fixture '.../dump2.json': [u"Select a valid choice.  u'ta' is not one of the available choices."]

**Comment by kelvinwong-ca** [comment]
This fix was released in 0.4.1
